import{a as v,i as p,S as h}from"./assets/vendor-C_7oAj77.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();document.querySelector(".list");function L(e){return e.map(q).join("")}function q(e){return`
    <li class='elem-list'>
        <div class="gallery">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" loading="lazy" alt="${e.tags}" title="${e.tags}" class='image'/>
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </div>
        </li>`}const a=document.querySelector(".loader"),b=document.querySelector(".list"),u=document.querySelector(".btn-more");u.style.display="none";a&&(a.style.display="none");const $="48428320-38598d28b4d5228a2fffcb2e3",x="https://pixabay.com/api/";async function S(e,s=1,r=20,c=!1){a&&(a.style.display="");const t=`${x}?key=${$}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${r}&page=${s}`;try{const i=(await v.get(t)).data;if(a&&(a.style.display="none"),!i.hits||i.hits.length===0){u.style.display="none",p.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});return}else{const f=L(i.hits);c?b.insertAdjacentHTML("beforeend",f):b.innerHTML=f,new h(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0}).refresh(),u.style.display=""}return i}catch(o){u.style.display="none",p.error({message:o.message,timeout:5e3,position:"topRight"}),a&&(a.style.display="none")}}const m=document.querySelector("#text"),w=document.querySelector(".list"),M=document.querySelector(".search"),y=document.querySelector(".loader"),n=document.querySelector(".btn-more");n.style.display="none";y.style.display="none";let d=1,g=15,l="";m.addEventListener("input",e=>{l=e.target.value,l.trim()===""&&(m.value="")});M.addEventListener("click",async e=>{if(e.preventDefault(),d=1,d===1&&(n.style.display="none"),w.innerHTML="",l=m.value.trim(),!l||l.trim()==="")return p.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});try{y.style.display="";const s=await S(l,d,g);if(y.style.display="none",!s.hits||s.hits.length===0)return p.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});w.innerHTML=L(s.hits),new h(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0}).refresh(),Math.ceil(s.totalHits/g)<=1?n.style.display="none":n.style.display=""}catch{y.style.display="none";return}});n.addEventListener("click",async()=>{d+=1;const e=document.querySelector(".list li"),s=e.getBoundingClientRect().height;requestAnimationFrame(()=>{window.scrollBy({top:s*2,behavior:"smooth"})});try{y.style.display="",n.style.display="none";const r=await S(l,d,g,!0);if(y.style.display="none",new h(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0}).refresh(),e){const o=e.getBoundingClientRect().height;requestAnimationFrame(()=>{window.scrollBy({top:o*2,behavior:"smooth"})})}const t=Math.ceil(r.totalHits/g);d>=t?(n.style.display="none",p.info({position:"topRight",message:"You've reached the end of the results"})):n.style.display=""}catch(r){n.style.display="none",console.log(r)}});
//# sourceMappingURL=index.js.map
