import{a as v,i as d,S as g}from"./assets/vendor-C_7oAj77.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();document.querySelector(".list");function L(e){return e.map($).join("")}function $(e){return`
    <li class='elem-list'>
        <div class="gallery">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" loading="lazy" alt="${e.tags}" title="${e.tags}" class='image'/>
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </div>
        </li>`}const i=document.querySelector(".loader"),f=document.querySelector(".list"),u=document.querySelector(".btn-more");u.style.display="none";i&&(i.style.display="none");const q="48428320-38598d28b4d5228a2fffcb2e3",x="https://pixabay.com/api/";async function S(e,o=1,r=20,l=!1){i&&(i.style.display="");const t=`${x}?key=${q}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${r}&page=${o}`;try{const n=(await v.get(t)).data;if(i&&(i.style.display="none"),!n.hits||n.hits.length===0){u.style.display="none",d.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});return}else{const m=L(n.hits);l?f.insertAdjacentHTML("beforeend",m):f.innerHTML=m,new g(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0}).refresh(),u.style.display=""}return n}catch(s){u.style.display="none",d.error({message:s.message,timeout:5e3,position:"topRight"}),i&&(i.style.display="none")}}const b=document.querySelector("#text"),w=document.querySelector(".list"),M=document.querySelector(".search"),y=document.querySelector(".loader"),a=document.querySelector(".btn-more");a.style.display="none";y.style.display="none";let c=1,h=15,p="";b.addEventListener("input",e=>{p=e.target.value,p.trim()===""&&(b.value="")});M.addEventListener("click",async e=>{if(e.preventDefault(),c=1,c===1&&(a.style.display="none"),w.innerHTML="",!p||p.trim()==="")return d.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});try{y.style.display="";const o=await S(p,c,h);if(y.style.display="none",!o.hits||o.hits.length===0)return d.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});w.innerHTML=L(o.hits),new g(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0}).refresh();const l=Math.ceil(o.totalHits/h);c>=l?(a.style.display="none",d.info({position:"topRight",message:"You've reached the end of the results"})):a.style.display=""}catch{y.style.display="none";return}});a.addEventListener("click",async()=>{c+=1;const e=document.querySelector(".list li"),o=e.getBoundingClientRect().height;y.style.display="",setTimeout(()=>{window.scrollBy({top:o*2,behavior:"smooth"})},100);try{const r=await S(p,c,h,!0);y.style.display="none",new g(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0}).refresh(),e&&window.scrollBy({top:o*2,behavior:"smooth"});const t=Math.ceil(r.totalHits/h);c>=t?(a.style.display="none",d.info({position:"topRight",message:"You've reached the end of the results"})):a.style.display=""}catch(r){a.style.display="none",console.log(r)}});
//# sourceMappingURL=index.js.map
