import{a as v,i as p,S as f}from"./assets/vendor-C_7oAj77.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&l(r)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();document.querySelector(".list");function S(e){return e.map(q).join("")}function q(e){return`
    <li class='elem-list'>
        <div class="gallery">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" loading="lazy" alt="${e.tags}" title="${e.tags}" class='image'/>
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </div>
        </li>`}const i=document.querySelector(".loader"),b=document.querySelector(".list"),u=document.querySelector(".btn-more");u.style.display="none";i&&(i.style.display="none");const $="48428320-38598d28b4d5228a2fffcb2e3",x="https://pixabay.com/api/";async function w(e,o=1,a=20,l=!1){i&&(i.style.display="");const t=`${x}?key=${$}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${a}&page=${o}`;try{const r=(await v.get(t)).data;if(i&&(i.style.display="none"),!r.hits||r.hits.length===0){u.style.display="none",p.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});return}else{const h=S(r.hits);l?b.insertAdjacentHTML("beforeend",h):b.innerHTML=h,new f(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0}).refresh(),u.style.display=""}return r}catch(s){u.style.display="none",p.error({message:s.message,timeout:5e3,position:"topRight"}),i&&(i.style.display="none")}}const g=document.querySelector("#text"),L=document.querySelector(".list"),M=document.querySelector(".search"),y=document.querySelector(".loader"),n=document.querySelector(".btn-more");n.style.display="none";y.style.display="none";let d=1,m=15,c="";g.addEventListener("input",e=>{c=e.target.value,c.trim()===""&&(g.value="")});M.addEventListener("click",async e=>{if(e.preventDefault(),d=1,d===1&&(n.style.display="none"),L.innerHTML="",c=g.value.trim(),!c||c.trim()==="")return p.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});try{y.style.display="";const o=await w(c,d,m);if(y.style.display="none",!o.hits||o.hits.length===0)return p.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});L.innerHTML=S(o.hits),new f(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0}).refresh(),Math.ceil(o.totalHits/m)<=1?n.style.display="none":n.style.display=""}catch{y.style.display="none";return}});n.addEventListener("click",async()=>{d+=1,y.style.display="",n.style.display="none";try{const e=await w(c,d,m,!0);y.style.display="none",new f(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0}).refresh();const a=document.querySelector(".list li");if(a){const t=a.getBoundingClientRect().height;requestAnimationFrame(()=>{window.scrollBy({top:t*2,behavior:"smooth"})})}const l=Math.ceil(e.totalHits/m);d>=l?(n.style.display="none",p.info({position:"topRight",message:"You've reached the end of the results"})):n.style.display=""}catch(e){y.style.display="none",n.style.display="none",console.log(e)}});
//# sourceMappingURL=index.js.map
